name: Deploy NPM Project to AWS BeanStalk

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docker
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Installing NPM
      run: npm install

    - name: Generate deployment package
      run: zip -r deploy.zip . -x "**node_modules**"
    
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
        
    - name: Configure AWS credentials
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        application_name: ${{ secrets.AWS_APP_NAME }}
        environment_name: ${{ secrets.AWS_ENV_NAME }}
        version_label: "prefletsupport-${{ steps.format-time.outputs.replaced }}"
        deployment_package: deploy.zip
